### ISSUE TITLE
Added Backup and restore all volumes in README.md

### ISSUE THREAD

**Issue by icasimpan** [icasimpan/vackup2#1]
Originally a PR from upstream project https://github.com/BretFisher/docker-vackup/pull/6 from @delfer

**Comment by Guiorgy** [comment]
As I noted in that [PR](https://github.com/BretFisher/docker-vackup/pull/6#issuecomment-1667706095), you should consider using the `-q` flag for `docker volume ls` instead of trying to parse the human readable output with awk which is unstable.
